# This is a sample .redhat-ci.yml which documents all the
# supported fields. You can validate your .redhat-ci.yml
# file by using the validator.py script. It must be in UTF-8
# format (though only fields denoted to support UTF-8 can
# contain non-ASCII values).

# REQUIRED (only one of 'host' or 'container' or 'cluster')
# Provision a single host.
host:
    # REQUIRED
    # Specify the distro to provision:
    #   - fedora/24/cloud
    #   - fedora/24/atomic
    #   - fedora/25/cloud
    #   - fedora/25/atomic
    #   - fedora/latest/atomic
    #   - centos/7/cloud
    #   - centos/7/atomic
    #   - centos/7/atomic/alpha
    #   - centos/7/atomic/continuous
    distro: fedora/25/cloud

    # OPTIONAL
    # Specify the minimum requirements the host must
    # fulfill. The values defined below are the defaults
    # used when no minimums are specified.
    specs:
      # OPTIONAL
      # Minimum amount of RAM in MB.
      ram: 2048
      # OPTIONAL
      # Minimum number of CPUs.
      cpus: 1
      # OPTIONAL
      # Minimum size of primary disk in GB.
      disk: 20
      # OPTIONAL
      # Minimum size of secondary disk in GB. Set to 0 if no
      # secondary disk is needed.
      secondary-disk: 0

    # OPTIONAL
    # If using an Atomic Host variant, you can specify which
    # ostree to use. To use the latest tree on the current
    # branch, use:
    ostree: latest

    # Otherwise, you may specify a tree by providing a dict:
    ostree:
      # OPTIONAL
      # Specify the remote to which to rebase. If omitted,
      # the current remote is used.
      remote: http://example.com/remote/repo
      # OPTIONAL
      # Specify the branch to which to rebase. If omitted,
      # the current branch is used.
      branch: my/branch
      # OPTIONAL
      # Specify the version or checksum to deploy. If
      # omitted, the latest commit is used.
      revision: 7.145.42


# OPTIONAL
# List the branches to test. If omitted, only the master
# branch is tested.
branches:
    - master


# OPTIONAL
# Whether this testsuite should run on pull requests. This
# is useful for example if you would like longer tests to
# only run on branches (for use with a merge bot). If
# omitted, defaults to true.
pulls: true

# OPTIONAL
# GitHub commit status context to use when reporting back
# status updates to GitHub. If omitted, defaults to
# 'Red Hat CI'.
context: 'CI Tester'

# OPTIONAL
# Mark this testsuite as required. This causes a special
# "required" context to be reported to GitHub on branch
# tests. The result is set to successful only if all
# testsuites marked as required are also successful. This is
# useful for integration with merge bots, so that they only
# need to watch for a single status rather than multiple
# (possibly changing) statuses. If omitted, defaults to
# false.
required: true

# OPTIONAL
# Additional YUM repositories to inject during provisioning.
extra-repos:
    - name: my-repo-name # REQUIRED key
      baseurl: https://example.com/repo
    - name: my-other-repo-name # REQUIRED key
      metalink: https://example.com/metalink?repo=mydistro
      gpgcheck: 0

# OPTIONAL
# List of packages to install during provisioning. If
# running on an Atomic Host variant, packages will be
# layered.
packages:
    - make
    - gcc
    - go-md2man
    - libyaml-devel
    - glib2-devel
    - json-glib-devel
    - autoconf


# REQUIRED (at least one of 'build' or 'tests')
# If the project follows the Build API (see
# https://github.com/cgwalters/build-api), you may specify
# the 'build' key to automatically build the code.
build: true


# REQUIRED (at least one of 'build' or 'tests')
# Put the tasks to be executed in the 'tests' key. They are
# run from the root of the repo. If the 'build' key is also
# present, tests will run after a successful build. Full
# UTF-8 values are supported.
tests:
    - make check

# OPTIONAL
# Time to allow before aborting tests. Must satisfy regex
# '[0-9]+[smh]'. If omitted, defaults to '2h', which is the
# maximum.
timeout: 30m

# OPTIONAL
# List of files/directories to upload to Amazon S3.
artifacts:
    - test-suite.log

---

